version: '3.8'

services:
  bi-mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bi-mcp.rule=Host(`bi-mcp.yourdomain.com`)"
      - "traefik.http.services.bi-mcp.loadbalancer.server.port=3000"